python Menopause_I.py \
	--out-dir out \
	--sib-mortality 1 \
	--mat-mortality 1 \
	--maternal-age-effect 1 \
	--lif-increase 0 \
	--epi-inherit 0 \
	--interbirth-interval 3 \
	--k-s 0.3 \
	--x0-s 4 \
	--L-s 2 \
	--U-curve-right-quadratic-term 0.008 \
	--U-curve-vertex-x 28 \
	--attenuation_cutoff 0.1 \
	--idx $1
