python Menopause_I.py \
	--out-dir out \
	--sib-mortality 0 \
	--mat-mortality 0 \
	--lif-increase 0 \
	--epi-inherit 0 \
	--maternal-age-effect 1 \
	--interbirth-interval 3 \
	--k-s 0.3 \
	--x0-s 5 \
	--L-s 2 \
	--attenuation_cutoff 0 \
	--idx $1
